interface Env {
  DB: D1Database;
  APP_STORAGE: R2Bucket;
  CLOUDFLARE_CREDENTIAL_ENCRYPTION_KEY?: string;
  CLOUDFLARE_OAUTH_CLIENT_ID?: string;
  CLOUDFLARE_OAUTH_CLIENT_SECRET?: string;
  CLOUDFLARE_OAUTH_SCOPES?: string;
  DEPLOYMENT_PROXY_JWT_SECRET?: string;
  WORKERS_CI_COMMIT_SHA?: string;
  COMMIT_SHA?: string;
  GITHUB_SHA?: string;
}
