/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AbuseRouteImport } from './routes/abuse';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as PrivacyRouteImport } from './routes/privacy';
import { Route as SecurityRouteImport } from './routes/security';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as SupportRouteImport } from './routes/support';
import { Route as TermsRouteImport } from './routes/terms';
import { Route as ChatIdRouteImport } from './routes/chat.$id';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AbuseRoute = AbuseRouteImport.update({
  id: '/abuse',
  path: '/abuse',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any);
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any);
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/abuse': typeof AbuseRoute;
  '/admin': typeof AdminRoute;
  '/privacy': typeof PrivacyRoute;
  '/security': typeof SecurityRoute;
  '/settings': typeof SettingsRoute;
  '/support': typeof SupportRoute;
  '/terms': typeof TermsRoute;
  '/chat/$id': typeof ChatIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/abuse': typeof AbuseRoute;
  '/admin': typeof AdminRoute;
  '/privacy': typeof PrivacyRoute;
  '/security': typeof SecurityRoute;
  '/settings': typeof SettingsRoute;
  '/support': typeof SupportRoute;
  '/terms': typeof TermsRoute;
  '/chat/$id': typeof ChatIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/abuse': typeof AbuseRoute;
  '/admin': typeof AdminRoute;
  '/privacy': typeof PrivacyRoute;
  '/security': typeof SecurityRoute;
  '/settings': typeof SettingsRoute;
  '/support': typeof SupportRoute;
  '/terms': typeof TermsRoute;
  '/chat/$id': typeof ChatIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/abuse'
    | '/admin'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/chat/$id';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/abuse'
    | '/admin'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/chat/$id';
  id:
    | '__root__'
    | '/'
    | '/abuse'
    | '/admin'
    | '/privacy'
    | '/security'
    | '/settings'
    | '/support'
    | '/terms'
    | '/chat/$id';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AbuseRoute: typeof AbuseRoute;
  AdminRoute: typeof AdminRoute;
  PrivacyRoute: typeof PrivacyRoute;
  SecurityRoute: typeof SecurityRoute;
  SettingsRoute: typeof SettingsRoute;
  SupportRoute: typeof SupportRoute;
  TermsRoute: typeof TermsRoute;
  ChatIdRoute: typeof ChatIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/abuse': {
      id: '/abuse';
      path: '/abuse';
      fullPath: '/abuse';
      preLoaderRoute: typeof AbuseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/privacy': {
      id: '/privacy';
      path: '/privacy';
      fullPath: '/privacy';
      preLoaderRoute: typeof PrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/security': {
      id: '/security';
      path: '/security';
      fullPath: '/security';
      preLoaderRoute: typeof SecurityRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/support': {
      id: '/support';
      path: '/support';
      fullPath: '/support';
      preLoaderRoute: typeof SupportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/terms': {
      id: '/terms';
      path: '/terms';
      fullPath: '/terms';
      preLoaderRoute: typeof TermsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat/$id': {
      id: '/chat/$id';
      path: '/chat/$id';
      fullPath: '/chat/$id';
      preLoaderRoute: typeof ChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbuseRoute: AbuseRoute,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ChatIdRoute: ChatIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
