/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as ShareRouteImport } from './routes/share';
import { Route as SettingsRouteImport } from './routes/settings';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ShareCodeRouteImport } from './routes/share.$code';
import { Route as CreateShareCodeRouteImport } from './routes/create.$shareCode';
import { Route as ChatIdRouteImport } from './routes/chat.$id';
import { Route as WebcontainerPreviewIdRouteImport } from './routes/webcontainer.preview.$id';
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$';

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ShareCodeRoute = ShareCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ShareRoute,
} as any);
const CreateShareCodeRoute = CreateShareCodeRouteImport.update({
  id: '/create/$shareCode',
  path: '/create/$shareCode',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const WebcontainerPreviewIdRoute = WebcontainerPreviewIdRouteImport.update({
  id: '/webcontainer/preview/$id',
  path: '/webcontainer/preview/$id',
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/share': typeof ShareRouteWithChildren;
  '/chat/$id': typeof ChatIdRoute;
  '/create/$shareCode': typeof CreateShareCodeRoute;
  '/share/$code': typeof ShareCodeRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/webcontainer/preview/$id': typeof WebcontainerPreviewIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/share': typeof ShareRouteWithChildren;
  '/chat/$id': typeof ChatIdRoute;
  '/create/$shareCode': typeof CreateShareCodeRoute;
  '/share/$code': typeof ShareCodeRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/webcontainer/preview/$id': typeof WebcontainerPreviewIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/settings': typeof SettingsRoute;
  '/share': typeof ShareRouteWithChildren;
  '/chat/$id': typeof ChatIdRoute;
  '/create/$shareCode': typeof CreateShareCodeRoute;
  '/share/$code': typeof ShareCodeRoute;
  '/api/auth/$': typeof ApiAuthSplatRoute;
  '/webcontainer/preview/$id': typeof WebcontainerPreviewIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/settings'
    | '/share'
    | '/chat/$id'
    | '/create/$shareCode'
    | '/share/$code'
    | '/api/auth/$'
    | '/webcontainer/preview/$id';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/settings'
    | '/share'
    | '/chat/$id'
    | '/create/$shareCode'
    | '/share/$code'
    | '/api/auth/$'
    | '/webcontainer/preview/$id';
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/share'
    | '/chat/$id'
    | '/create/$shareCode'
    | '/share/$code'
    | '/api/auth/$'
    | '/webcontainer/preview/$id';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  ShareRoute: typeof ShareRouteWithChildren;
  ChatIdRoute: typeof ChatIdRoute;
  CreateShareCodeRoute: typeof CreateShareCodeRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  WebcontainerPreviewIdRoute: typeof WebcontainerPreviewIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share';
      path: '/share';
      fullPath: '/share';
      preLoaderRoute: typeof ShareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/settings': {
      id: '/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/share/$code': {
      id: '/share/$code';
      path: '/$code';
      fullPath: '/share/$code';
      preLoaderRoute: typeof ShareCodeRouteImport;
      parentRoute: typeof ShareRoute;
    };
    '/create/$shareCode': {
      id: '/create/$shareCode';
      path: '/create/$shareCode';
      fullPath: '/create/$shareCode';
      preLoaderRoute: typeof CreateShareCodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat/$id': {
      id: '/chat/$id';
      path: '/chat/$id';
      fullPath: '/chat/$id';
      preLoaderRoute: typeof ChatIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/webcontainer/preview/$id': {
      id: '/webcontainer/preview/$id';
      path: '/webcontainer/preview/$id';
      fullPath: '/webcontainer/preview/$id';
      preLoaderRoute: typeof WebcontainerPreviewIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/api/auth/$': {
      id: '/api/auth/$';
      path: '/api/auth/$';
      fullPath: '/api/auth/$';
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ShareRouteChildren {
  ShareCodeRoute: typeof ShareCodeRoute;
}

const ShareRouteChildren: ShareRouteChildren = {
  ShareCodeRoute: ShareCodeRoute,
};

const ShareRouteWithChildren = ShareRoute._addFileChildren(ShareRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRouteWithChildren,
  ChatIdRoute: ChatIdRoute,
  CreateShareCodeRoute: CreateShareCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  WebcontainerPreviewIdRoute: WebcontainerPreviewIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
