import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "jsonc-parser";

const WRANGLER_TYPES_TIMEOUT_MS = readTimeoutMs(
  process.env.CF_TYPEGEN_TIMEOUT_MS,
);

const TYPE_FILE = "worker-configuration.d.ts";

const result = spawnSync("wrangler", ["types", "--include-runtime", "false"], {
  encoding: "utf8",
  killSignal: "SIGTERM",
  shell: process.platform === "win32",
  timeout: WRANGLER_TYPES_TIMEOUT_MS,
});

if (result.stdout) {
  process.stdout.write(result.stdout);
}

if (result.stderr) {
  process.stderr.write(result.stderr);
}

if (result.status === 0) {
  ensurePackagedRuntimeTypes(TYPE_FILE);
  process.exit(0);
}

const output = `${result.stdout ?? ""}\n${result.stderr ?? ""}\n${
  result.error?.message ?? ""
}`;

if (!shouldGenerateEnvOnlyTypes(result, output)) {
  process.exit(result.status ?? 1);
}

console.warn(
  "wrangler types could not complete in this browser container; writing env-only Cloudflare binding types.",
);
await writeEnvOnlyTypes();

function shouldGenerateEnvOnlyTypes(result, output) {
  return isWranglerTypesTimeout(result) || isWorkerdStartupFailure(output);
}

function readTimeoutMs(value) {
  const parsed = Number.parseInt(value ?? "15000", 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 15_000;
}

function isWranglerTypesTimeout(result) {
  return result.error?.code === "ETIMEDOUT" || result.signal === "SIGTERM";
}

function isWorkerdStartupFailure(output) {
  return (
    output.includes("The Workers runtime failed to start") ||
    output.includes("workerd binary") ||
    output.includes("@cloudflare/workerd")
  );
}

function withPackagedRuntimeTypes(content) {
  const runtimeReference =
    '/// <reference types="@cloudflare/workers-types" />';

  if (content.includes(runtimeReference)) {
    return content;
  }

  return `${runtimeReference}\n${content}`;
}

function ensurePackagedRuntimeTypes(path) {
  const content = readFileSync(path, "utf8");
  writeFileSync(path, withPackagedRuntimeTypes(content));
}

async function writeEnvOnlyTypes() {
  try {
    const { experimental_generateTypes } = await import("wrangler");

    if (typeof experimental_generateTypes === "function") {
      const generated = await experimental_generateTypes({
        config: "wrangler.jsonc",
        includeEnv: true,
        includeRuntime: false,
        path: TYPE_FILE,
      });
      writeFileSync(
        generated.path,
        withPackagedRuntimeTypes(generated.content),
      );
      return;
    }
  } catch (error) {
    console.warn(
      `Wrangler's type generation API failed; falling back to a local binding-type renderer. ${error}`,
    );
  }

  writeFileSync(TYPE_FILE, renderFallbackTypes(readWranglerConfig()));
}

function readWranglerConfig() {
  return parse(readFileSync("wrangler.jsonc", "utf8"));
}

function bindingName(value) {
  return typeof value === "string" && value.trim() ? value.trim() : null;
}

function addBinding(lines, name, type) {
  const safeName = bindingName(name);

  if (!safeName) {
    return;
  }

  lines.push(`  ${safeName}: ${type};`);
}

function renderFallbackTypes(config) {
  const envLines = [];
  const durableNamespaces = [];

  for (const binding of config?.d1_databases ?? []) {
    addBinding(envLines, binding?.binding, "D1Database");
  }

  for (const binding of config?.r2_buckets ?? []) {
    addBinding(envLines, binding?.binding, "R2Bucket");
  }

  if (config?.ai?.binding) {
    addBinding(envLines, config.ai.binding, "Ai");
  }

  for (const binding of config?.kv_namespaces ?? []) {
    addBinding(envLines, binding?.binding, "KVNamespace");
  }

  for (const binding of config?.queues?.producers ?? []) {
    addBinding(envLines, binding?.binding, "Queue");
  }

  for (const binding of config?.vectorize ?? []) {
    addBinding(envLines, binding?.binding, "VectorizeIndex");
  }

  for (const binding of config?.durable_objects?.bindings ?? []) {
    const name = bindingName(binding?.name);
    const className = bindingName(binding?.class_name);

    if (!name || !className) {
      continue;
    }

    envLines.push(
      `  ${name}: DurableObjectNamespace<import("./src/server").${className}>;`,
    );
    durableNamespaces.push(JSON.stringify(name));
  }

  for (const name of Object.keys(config?.vars ?? {})) {
    addBinding(envLines, name, "string");
  }

  const durableNamespaceType =
    durableNamespaces.length > 0 ? durableNamespaces.join(" | ") : "never";

  return `/* eslint-disable */
// Generated by scripts/cf-typegen.mjs after wrangler types could not start workerd.
/// <reference types="@cloudflare/workers-types" />

interface __BaseEnv_Env {
${envLines.sort().join("\n")}
}

declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: ${durableNamespaceType};
  }
  interface Env extends __BaseEnv_Env {}
}

interface Env extends __BaseEnv_Env {}
`;
}
