import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/preview/$workerName')({
  component: PreviewWorkerRoute,
})

function PreviewWorkerRoute() {
  const { workerName } = Route.useParams()
  const title = workerName
    .split('-')
    .filter(Boolean)
    .map((word) => `${word[0]?.toUpperCase() ?? ''}${word.slice(1)}`)
    .join(' ')

  return (
    <main className="generated-preview-page">
      <section>
        <span>GhostBuild Preview</span>
        <h1>{title || workerName}</h1>
        <p>
          This preview route is generated by GhostBuild before Cloudflare deploy.
          It verifies the Worker URL, health path, and deploy gate with a real
          app route instead of a static placeholder.
        </p>
        <a href={`/preview/${workerName}/api/health`}>Health check</a>
      </section>
    </main>
  )
}
