/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewWorkerNameRouteImport } from './routes/preview/$workerName'
import { Route as ApiPlanRouteImport } from './routes/api.plan'
import { Route as ApiBuilderSessionsRouteImport } from './routes/api/builder-sessions'
import { Route as ApiStripeProjectsStatusRouteImport } from './routes/api/stripe-projects/status'
import { Route as ApiStripeProjectsDisconnectRouteImport } from './routes/api/stripe-projects/disconnect'
import { Route as ApiStripeProjectsConnectRouteImport } from './routes/api/stripe-projects/connect'
import { Route as ApiStripeProjectsCallbackRouteImport } from './routes/api/stripe-projects/callback'
import { Route as ApiRuntimeActionRouteImport } from './routes/api/runtime/action'
import { Route as ApiDeployWorkerRouteImport } from './routes/api/deploy/worker'
import { Route as ApiDeployRunRouteImport } from './routes/api/deploy/run'
import { Route as ApiDeployApprovalRouteImport } from './routes/api/deploy/approval'
import { Route as ApiCloudflareStatusRouteImport } from './routes/api/cloudflare/status'
import { Route as ApiCloudflareDisconnectRouteImport } from './routes/api/cloudflare/disconnect'
import { Route as ApiCloudflareConnectRouteImport } from './routes/api/cloudflare/connect'
import { Route as ApiCloudflareMcpStatusRouteImport } from './routes/api/cloudflare-mcp/status'
import { Route as ApiCloudflareMcpConnectRouteImport } from './routes/api/cloudflare-mcp/connect'
import { Route as ApiBuildRunRouteImport } from './routes/api/build/run'
import { Route as ApiBuildRepairRouteImport } from './routes/api/build/repair'
import { Route as ApiBuildPreviewRouteImport } from './routes/api/build/preview'
import { Route as ApiBuildPatchRouteImport } from './routes/api/build/patch'
import { Route as ApiBuildGenerateRouteImport } from './routes/api/build/generate'
import { Route as ApiBuildChecksRouteImport } from './routes/api/build/checks'
import { Route as ApiBuildAgentPatchRouteImport } from './routes/api/build/agent-patch'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAppAuthStatusRouteImport } from './routes/api/app-auth/status'
import { Route as ApiAppAuthLogoutRouteImport } from './routes/api/app-auth/logout'
import { Route as PreviewWorkerNameApiHealthRouteImport } from './routes/preview/$workerName/api/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewWorkerNameRoute = PreviewWorkerNameRouteImport.update({
  id: '/preview/$workerName',
  path: '/preview/$workerName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuilderSessionsRoute = ApiBuilderSessionsRouteImport.update({
  id: '/api/builder-sessions',
  path: '/api/builder-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeProjectsStatusRoute = ApiStripeProjectsStatusRouteImport.update({
  id: '/api/stripe-projects/status',
  path: '/api/stripe-projects/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeProjectsDisconnectRoute =
  ApiStripeProjectsDisconnectRouteImport.update({
    id: '/api/stripe-projects/disconnect',
    path: '/api/stripe-projects/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeProjectsConnectRoute =
  ApiStripeProjectsConnectRouteImport.update({
    id: '/api/stripe-projects/connect',
    path: '/api/stripe-projects/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeProjectsCallbackRoute =
  ApiStripeProjectsCallbackRouteImport.update({
    id: '/api/stripe-projects/callback',
    path: '/api/stripe-projects/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRuntimeActionRoute = ApiRuntimeActionRouteImport.update({
  id: '/api/runtime/action',
  path: '/api/runtime/action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeployWorkerRoute = ApiDeployWorkerRouteImport.update({
  id: '/api/deploy/worker',
  path: '/api/deploy/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeployRunRoute = ApiDeployRunRouteImport.update({
  id: '/api/deploy/run',
  path: '/api/deploy/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeployApprovalRoute = ApiDeployApprovalRouteImport.update({
  id: '/api/deploy/approval',
  path: '/api/deploy/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareStatusRoute = ApiCloudflareStatusRouteImport.update({
  id: '/api/cloudflare/status',
  path: '/api/cloudflare/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareDisconnectRoute = ApiCloudflareDisconnectRouteImport.update({
  id: '/api/cloudflare/disconnect',
  path: '/api/cloudflare/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareConnectRoute = ApiCloudflareConnectRouteImport.update({
  id: '/api/cloudflare/connect',
  path: '/api/cloudflare/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareMcpStatusRoute = ApiCloudflareMcpStatusRouteImport.update({
  id: '/api/cloudflare-mcp/status',
  path: '/api/cloudflare-mcp/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudflareMcpConnectRoute = ApiCloudflareMcpConnectRouteImport.update({
  id: '/api/cloudflare-mcp/connect',
  path: '/api/cloudflare-mcp/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRunRoute = ApiBuildRunRouteImport.update({
  id: '/api/build/run',
  path: '/api/build/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildRepairRoute = ApiBuildRepairRouteImport.update({
  id: '/api/build/repair',
  path: '/api/build/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildPreviewRoute = ApiBuildPreviewRouteImport.update({
  id: '/api/build/preview',
  path: '/api/build/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildPatchRoute = ApiBuildPatchRouteImport.update({
  id: '/api/build/patch',
  path: '/api/build/patch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildGenerateRoute = ApiBuildGenerateRouteImport.update({
  id: '/api/build/generate',
  path: '/api/build/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildChecksRoute = ApiBuildChecksRouteImport.update({
  id: '/api/build/checks',
  path: '/api/build/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildAgentPatchRoute = ApiBuildAgentPatchRouteImport.update({
  id: '/api/build/agent-patch',
  path: '/api/build/agent-patch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppAuthStatusRoute = ApiAppAuthStatusRouteImport.update({
  id: '/api/app-auth/status',
  path: '/api/app-auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppAuthLogoutRoute = ApiAppAuthLogoutRouteImport.update({
  id: '/api/app-auth/logout',
  path: '/api/app-auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewWorkerNameApiHealthRoute =
  PreviewWorkerNameApiHealthRouteImport.update({
    id: '/api/health',
    path: '/api/health',
    getParentRoute: () => PreviewWorkerNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/builder-sessions': typeof ApiBuilderSessionsRoute
  '/api/plan': typeof ApiPlanRoute
  '/preview/$workerName': typeof PreviewWorkerNameRouteWithChildren
  '/api/app-auth/logout': typeof ApiAppAuthLogoutRoute
  '/api/app-auth/status': typeof ApiAppAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/agent-patch': typeof ApiBuildAgentPatchRoute
  '/api/build/checks': typeof ApiBuildChecksRoute
  '/api/build/generate': typeof ApiBuildGenerateRoute
  '/api/build/patch': typeof ApiBuildPatchRoute
  '/api/build/preview': typeof ApiBuildPreviewRoute
  '/api/build/repair': typeof ApiBuildRepairRoute
  '/api/build/run': typeof ApiBuildRunRoute
  '/api/cloudflare-mcp/connect': typeof ApiCloudflareMcpConnectRoute
  '/api/cloudflare-mcp/status': typeof ApiCloudflareMcpStatusRoute
  '/api/cloudflare/connect': typeof ApiCloudflareConnectRoute
  '/api/cloudflare/disconnect': typeof ApiCloudflareDisconnectRoute
  '/api/cloudflare/status': typeof ApiCloudflareStatusRoute
  '/api/deploy/approval': typeof ApiDeployApprovalRoute
  '/api/deploy/run': typeof ApiDeployRunRoute
  '/api/deploy/worker': typeof ApiDeployWorkerRoute
  '/api/runtime/action': typeof ApiRuntimeActionRoute
  '/api/stripe-projects/callback': typeof ApiStripeProjectsCallbackRoute
  '/api/stripe-projects/connect': typeof ApiStripeProjectsConnectRoute
  '/api/stripe-projects/disconnect': typeof ApiStripeProjectsDisconnectRoute
  '/api/stripe-projects/status': typeof ApiStripeProjectsStatusRoute
  '/preview/$workerName/api/health': typeof PreviewWorkerNameApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/builder-sessions': typeof ApiBuilderSessionsRoute
  '/api/plan': typeof ApiPlanRoute
  '/preview/$workerName': typeof PreviewWorkerNameRouteWithChildren
  '/api/app-auth/logout': typeof ApiAppAuthLogoutRoute
  '/api/app-auth/status': typeof ApiAppAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/agent-patch': typeof ApiBuildAgentPatchRoute
  '/api/build/checks': typeof ApiBuildChecksRoute
  '/api/build/generate': typeof ApiBuildGenerateRoute
  '/api/build/patch': typeof ApiBuildPatchRoute
  '/api/build/preview': typeof ApiBuildPreviewRoute
  '/api/build/repair': typeof ApiBuildRepairRoute
  '/api/build/run': typeof ApiBuildRunRoute
  '/api/cloudflare-mcp/connect': typeof ApiCloudflareMcpConnectRoute
  '/api/cloudflare-mcp/status': typeof ApiCloudflareMcpStatusRoute
  '/api/cloudflare/connect': typeof ApiCloudflareConnectRoute
  '/api/cloudflare/disconnect': typeof ApiCloudflareDisconnectRoute
  '/api/cloudflare/status': typeof ApiCloudflareStatusRoute
  '/api/deploy/approval': typeof ApiDeployApprovalRoute
  '/api/deploy/run': typeof ApiDeployRunRoute
  '/api/deploy/worker': typeof ApiDeployWorkerRoute
  '/api/runtime/action': typeof ApiRuntimeActionRoute
  '/api/stripe-projects/callback': typeof ApiStripeProjectsCallbackRoute
  '/api/stripe-projects/connect': typeof ApiStripeProjectsConnectRoute
  '/api/stripe-projects/disconnect': typeof ApiStripeProjectsDisconnectRoute
  '/api/stripe-projects/status': typeof ApiStripeProjectsStatusRoute
  '/preview/$workerName/api/health': typeof PreviewWorkerNameApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/builder-sessions': typeof ApiBuilderSessionsRoute
  '/api/plan': typeof ApiPlanRoute
  '/preview/$workerName': typeof PreviewWorkerNameRouteWithChildren
  '/api/app-auth/logout': typeof ApiAppAuthLogoutRoute
  '/api/app-auth/status': typeof ApiAppAuthStatusRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/build/agent-patch': typeof ApiBuildAgentPatchRoute
  '/api/build/checks': typeof ApiBuildChecksRoute
  '/api/build/generate': typeof ApiBuildGenerateRoute
  '/api/build/patch': typeof ApiBuildPatchRoute
  '/api/build/preview': typeof ApiBuildPreviewRoute
  '/api/build/repair': typeof ApiBuildRepairRoute
  '/api/build/run': typeof ApiBuildRunRoute
  '/api/cloudflare-mcp/connect': typeof ApiCloudflareMcpConnectRoute
  '/api/cloudflare-mcp/status': typeof ApiCloudflareMcpStatusRoute
  '/api/cloudflare/connect': typeof ApiCloudflareConnectRoute
  '/api/cloudflare/disconnect': typeof ApiCloudflareDisconnectRoute
  '/api/cloudflare/status': typeof ApiCloudflareStatusRoute
  '/api/deploy/approval': typeof ApiDeployApprovalRoute
  '/api/deploy/run': typeof ApiDeployRunRoute
  '/api/deploy/worker': typeof ApiDeployWorkerRoute
  '/api/runtime/action': typeof ApiRuntimeActionRoute
  '/api/stripe-projects/callback': typeof ApiStripeProjectsCallbackRoute
  '/api/stripe-projects/connect': typeof ApiStripeProjectsConnectRoute
  '/api/stripe-projects/disconnect': typeof ApiStripeProjectsDisconnectRoute
  '/api/stripe-projects/status': typeof ApiStripeProjectsStatusRoute
  '/preview/$workerName/api/health': typeof PreviewWorkerNameApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/builder-sessions'
    | '/api/plan'
    | '/preview/$workerName'
    | '/api/app-auth/logout'
    | '/api/app-auth/status'
    | '/api/auth/$'
    | '/api/build/agent-patch'
    | '/api/build/checks'
    | '/api/build/generate'
    | '/api/build/patch'
    | '/api/build/preview'
    | '/api/build/repair'
    | '/api/build/run'
    | '/api/cloudflare-mcp/connect'
    | '/api/cloudflare-mcp/status'
    | '/api/cloudflare/connect'
    | '/api/cloudflare/disconnect'
    | '/api/cloudflare/status'
    | '/api/deploy/approval'
    | '/api/deploy/run'
    | '/api/deploy/worker'
    | '/api/runtime/action'
    | '/api/stripe-projects/callback'
    | '/api/stripe-projects/connect'
    | '/api/stripe-projects/disconnect'
    | '/api/stripe-projects/status'
    | '/preview/$workerName/api/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/builder-sessions'
    | '/api/plan'
    | '/preview/$workerName'
    | '/api/app-auth/logout'
    | '/api/app-auth/status'
    | '/api/auth/$'
    | '/api/build/agent-patch'
    | '/api/build/checks'
    | '/api/build/generate'
    | '/api/build/patch'
    | '/api/build/preview'
    | '/api/build/repair'
    | '/api/build/run'
    | '/api/cloudflare-mcp/connect'
    | '/api/cloudflare-mcp/status'
    | '/api/cloudflare/connect'
    | '/api/cloudflare/disconnect'
    | '/api/cloudflare/status'
    | '/api/deploy/approval'
    | '/api/deploy/run'
    | '/api/deploy/worker'
    | '/api/runtime/action'
    | '/api/stripe-projects/callback'
    | '/api/stripe-projects/connect'
    | '/api/stripe-projects/disconnect'
    | '/api/stripe-projects/status'
    | '/preview/$workerName/api/health'
  id:
    | '__root__'
    | '/'
    | '/api/builder-sessions'
    | '/api/plan'
    | '/preview/$workerName'
    | '/api/app-auth/logout'
    | '/api/app-auth/status'
    | '/api/auth/$'
    | '/api/build/agent-patch'
    | '/api/build/checks'
    | '/api/build/generate'
    | '/api/build/patch'
    | '/api/build/preview'
    | '/api/build/repair'
    | '/api/build/run'
    | '/api/cloudflare-mcp/connect'
    | '/api/cloudflare-mcp/status'
    | '/api/cloudflare/connect'
    | '/api/cloudflare/disconnect'
    | '/api/cloudflare/status'
    | '/api/deploy/approval'
    | '/api/deploy/run'
    | '/api/deploy/worker'
    | '/api/runtime/action'
    | '/api/stripe-projects/callback'
    | '/api/stripe-projects/connect'
    | '/api/stripe-projects/disconnect'
    | '/api/stripe-projects/status'
    | '/preview/$workerName/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBuilderSessionsRoute: typeof ApiBuilderSessionsRoute
  ApiPlanRoute: typeof ApiPlanRoute
  PreviewWorkerNameRoute: typeof PreviewWorkerNameRouteWithChildren
  ApiAppAuthLogoutRoute: typeof ApiAppAuthLogoutRoute
  ApiAppAuthStatusRoute: typeof ApiAppAuthStatusRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildAgentPatchRoute: typeof ApiBuildAgentPatchRoute
  ApiBuildChecksRoute: typeof ApiBuildChecksRoute
  ApiBuildGenerateRoute: typeof ApiBuildGenerateRoute
  ApiBuildPatchRoute: typeof ApiBuildPatchRoute
  ApiBuildPreviewRoute: typeof ApiBuildPreviewRoute
  ApiBuildRepairRoute: typeof ApiBuildRepairRoute
  ApiBuildRunRoute: typeof ApiBuildRunRoute
  ApiCloudflareMcpConnectRoute: typeof ApiCloudflareMcpConnectRoute
  ApiCloudflareMcpStatusRoute: typeof ApiCloudflareMcpStatusRoute
  ApiCloudflareConnectRoute: typeof ApiCloudflareConnectRoute
  ApiCloudflareDisconnectRoute: typeof ApiCloudflareDisconnectRoute
  ApiCloudflareStatusRoute: typeof ApiCloudflareStatusRoute
  ApiDeployApprovalRoute: typeof ApiDeployApprovalRoute
  ApiDeployRunRoute: typeof ApiDeployRunRoute
  ApiDeployWorkerRoute: typeof ApiDeployWorkerRoute
  ApiRuntimeActionRoute: typeof ApiRuntimeActionRoute
  ApiStripeProjectsCallbackRoute: typeof ApiStripeProjectsCallbackRoute
  ApiStripeProjectsConnectRoute: typeof ApiStripeProjectsConnectRoute
  ApiStripeProjectsDisconnectRoute: typeof ApiStripeProjectsDisconnectRoute
  ApiStripeProjectsStatusRoute: typeof ApiStripeProjectsStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$workerName': {
      id: '/preview/$workerName'
      path: '/preview/$workerName'
      fullPath: '/preview/$workerName'
      preLoaderRoute: typeof PreviewWorkerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builder-sessions': {
      id: '/api/builder-sessions'
      path: '/api/builder-sessions'
      fullPath: '/api/builder-sessions'
      preLoaderRoute: typeof ApiBuilderSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-projects/status': {
      id: '/api/stripe-projects/status'
      path: '/api/stripe-projects/status'
      fullPath: '/api/stripe-projects/status'
      preLoaderRoute: typeof ApiStripeProjectsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-projects/disconnect': {
      id: '/api/stripe-projects/disconnect'
      path: '/api/stripe-projects/disconnect'
      fullPath: '/api/stripe-projects/disconnect'
      preLoaderRoute: typeof ApiStripeProjectsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-projects/connect': {
      id: '/api/stripe-projects/connect'
      path: '/api/stripe-projects/connect'
      fullPath: '/api/stripe-projects/connect'
      preLoaderRoute: typeof ApiStripeProjectsConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-projects/callback': {
      id: '/api/stripe-projects/callback'
      path: '/api/stripe-projects/callback'
      fullPath: '/api/stripe-projects/callback'
      preLoaderRoute: typeof ApiStripeProjectsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/action': {
      id: '/api/runtime/action'
      path: '/api/runtime/action'
      fullPath: '/api/runtime/action'
      preLoaderRoute: typeof ApiRuntimeActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deploy/worker': {
      id: '/api/deploy/worker'
      path: '/api/deploy/worker'
      fullPath: '/api/deploy/worker'
      preLoaderRoute: typeof ApiDeployWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deploy/run': {
      id: '/api/deploy/run'
      path: '/api/deploy/run'
      fullPath: '/api/deploy/run'
      preLoaderRoute: typeof ApiDeployRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deploy/approval': {
      id: '/api/deploy/approval'
      path: '/api/deploy/approval'
      fullPath: '/api/deploy/approval'
      preLoaderRoute: typeof ApiDeployApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/status': {
      id: '/api/cloudflare/status'
      path: '/api/cloudflare/status'
      fullPath: '/api/cloudflare/status'
      preLoaderRoute: typeof ApiCloudflareStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/disconnect': {
      id: '/api/cloudflare/disconnect'
      path: '/api/cloudflare/disconnect'
      fullPath: '/api/cloudflare/disconnect'
      preLoaderRoute: typeof ApiCloudflareDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare/connect': {
      id: '/api/cloudflare/connect'
      path: '/api/cloudflare/connect'
      fullPath: '/api/cloudflare/connect'
      preLoaderRoute: typeof ApiCloudflareConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare-mcp/status': {
      id: '/api/cloudflare-mcp/status'
      path: '/api/cloudflare-mcp/status'
      fullPath: '/api/cloudflare-mcp/status'
      preLoaderRoute: typeof ApiCloudflareMcpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloudflare-mcp/connect': {
      id: '/api/cloudflare-mcp/connect'
      path: '/api/cloudflare-mcp/connect'
      fullPath: '/api/cloudflare-mcp/connect'
      preLoaderRoute: typeof ApiCloudflareMcpConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/run': {
      id: '/api/build/run'
      path: '/api/build/run'
      fullPath: '/api/build/run'
      preLoaderRoute: typeof ApiBuildRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/repair': {
      id: '/api/build/repair'
      path: '/api/build/repair'
      fullPath: '/api/build/repair'
      preLoaderRoute: typeof ApiBuildRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/preview': {
      id: '/api/build/preview'
      path: '/api/build/preview'
      fullPath: '/api/build/preview'
      preLoaderRoute: typeof ApiBuildPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/patch': {
      id: '/api/build/patch'
      path: '/api/build/patch'
      fullPath: '/api/build/patch'
      preLoaderRoute: typeof ApiBuildPatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/generate': {
      id: '/api/build/generate'
      path: '/api/build/generate'
      fullPath: '/api/build/generate'
      preLoaderRoute: typeof ApiBuildGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/checks': {
      id: '/api/build/checks'
      path: '/api/build/checks'
      fullPath: '/api/build/checks'
      preLoaderRoute: typeof ApiBuildChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/build/agent-patch': {
      id: '/api/build/agent-patch'
      path: '/api/build/agent-patch'
      fullPath: '/api/build/agent-patch'
      preLoaderRoute: typeof ApiBuildAgentPatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-auth/status': {
      id: '/api/app-auth/status'
      path: '/api/app-auth/status'
      fullPath: '/api/app-auth/status'
      preLoaderRoute: typeof ApiAppAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-auth/logout': {
      id: '/api/app-auth/logout'
      path: '/api/app-auth/logout'
      fullPath: '/api/app-auth/logout'
      preLoaderRoute: typeof ApiAppAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$workerName/api/health': {
      id: '/preview/$workerName/api/health'
      path: '/api/health'
      fullPath: '/preview/$workerName/api/health'
      preLoaderRoute: typeof PreviewWorkerNameApiHealthRouteImport
      parentRoute: typeof PreviewWorkerNameRoute
    }
  }
}

interface PreviewWorkerNameRouteChildren {
  PreviewWorkerNameApiHealthRoute: typeof PreviewWorkerNameApiHealthRoute
}

const PreviewWorkerNameRouteChildren: PreviewWorkerNameRouteChildren = {
  PreviewWorkerNameApiHealthRoute: PreviewWorkerNameApiHealthRoute,
}

const PreviewWorkerNameRouteWithChildren =
  PreviewWorkerNameRoute._addFileChildren(PreviewWorkerNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBuilderSessionsRoute: ApiBuilderSessionsRoute,
  ApiPlanRoute: ApiPlanRoute,
  PreviewWorkerNameRoute: PreviewWorkerNameRouteWithChildren,
  ApiAppAuthLogoutRoute: ApiAppAuthLogoutRoute,
  ApiAppAuthStatusRoute: ApiAppAuthStatusRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildAgentPatchRoute: ApiBuildAgentPatchRoute,
  ApiBuildChecksRoute: ApiBuildChecksRoute,
  ApiBuildGenerateRoute: ApiBuildGenerateRoute,
  ApiBuildPatchRoute: ApiBuildPatchRoute,
  ApiBuildPreviewRoute: ApiBuildPreviewRoute,
  ApiBuildRepairRoute: ApiBuildRepairRoute,
  ApiBuildRunRoute: ApiBuildRunRoute,
  ApiCloudflareMcpConnectRoute: ApiCloudflareMcpConnectRoute,
  ApiCloudflareMcpStatusRoute: ApiCloudflareMcpStatusRoute,
  ApiCloudflareConnectRoute: ApiCloudflareConnectRoute,
  ApiCloudflareDisconnectRoute: ApiCloudflareDisconnectRoute,
  ApiCloudflareStatusRoute: ApiCloudflareStatusRoute,
  ApiDeployApprovalRoute: ApiDeployApprovalRoute,
  ApiDeployRunRoute: ApiDeployRunRoute,
  ApiDeployWorkerRoute: ApiDeployWorkerRoute,
  ApiRuntimeActionRoute: ApiRuntimeActionRoute,
  ApiStripeProjectsCallbackRoute: ApiStripeProjectsCallbackRoute,
  ApiStripeProjectsConnectRoute: ApiStripeProjectsConnectRoute,
  ApiStripeProjectsDisconnectRoute: ApiStripeProjectsDisconnectRoute,
  ApiStripeProjectsStatusRoute: ApiStripeProjectsStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
