name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-and-build

      - name: Validate repository
        run: pnpm run validate
